version: '3.9'

services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma_db:/data
    ports:
      - "8000:8000"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .env:/app/.env

volumes:
  chroma_db:
